version: "3.9"

services:
  backend:
    build: ./backend
    container_name: emotion-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    environment:
      - FLASK_ENV=development
