name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Última versão estável para Ubuntu 22.04 é 3.10.17
          check-latest: true

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          cd backend
          python -m unittest discover -s tests -p "*.py"

      - name: Lint Python Code
        run: |
          cd backend
          pylint server.py EmotionDetection/*.py

  docker-build:
    runs-on: ubuntu-22.04
    needs: build-and-test
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t emotion-backend .

      - name: Optionally push to Docker Hub
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          docker tag emotion-backend $DOCKER_HUB_USERNAME/emotion-backend:latest
          docker push $DOCKER_HUB_USERNAME/emotion-backend:latest
